# Generated by Django 4.0.4 on 2022-05-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
